# Generated by Django 5.2 on 2025-07-03 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
