# Generated by Django 5.2 on 2025-06-26 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0002_payments_razorpay_payment_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments',
            name='payment_id',
        ),
        migrations.AddField(
            model_name='payments',
            name='razorpay_order_id',
            field=models.CharField(default='', max_length=200),
        ),
    ]
