# Generated by Django 5.2 on 2025-08-06 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0004_registration_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentgateway',
            name='payment_qr',
            field=models.ImageField(blank=True, null=True, upload_to='payment/', verbose_name='Payment QR'),
        ),
        migrations.AddField(
            model_name='paymentgateway',
            name='payment_upi_id',
            field=models.CharField(blank=True, help_text='Enter your Payment UPI ID.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paymentgateway',
            name='use',
            field=models.CharField(choices=[('RAZORPAY', 'RAZORPAY'), ('MANUAL', 'MANUAL')], default='RAZORPAY', max_length=10),
        ),
    ]
