# Generated by Django 5.2 on 2025-10-07 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0006_manualpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentgateway',
            name='use',
            field=models.CharField(choices=[('RAZORPAY', 'RAZORPAY'), ('MANUAL', 'MANUAL'), ('UPI GATEWAY', 'UPI GATEWAY')], default='RAZORPAY', max_length=12),
        ),
    ]
