# Generated by Django 5.2 on 2025-10-07 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0007_alter_paymentgateway_use'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentgateway',
            name='gateway_key',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='paymentgateway',
            name='gateway_url',
            field=models.URLField(default='https://mrtt.org.in'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='razorpay_order_id',
            field=models.CharField(default='', max_length=200, verbose_name='Order ID'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='razorpay_payment_id',
            field=models.CharField(default='', max_length=200, verbose_name='Payment ID'),
        ),
    ]
