# Generated by Django 5.2 on 2025-07-15 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_referral_code_customuser_referred_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_donated',
            new_name='registration_fee_paid',
        ),
        migrations.AddField(
            model_name='customuser',
            name='amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
