# Generated by Django 5.2 on 2025-08-21 15:37

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelfieWithTree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selfie_image', models.ImageField(upload_to=accounts.models.selfie_upload_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tree_selfies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Selfie with Tree',
                'verbose_name_plural': 'Selfies with Trees',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
