# Generated by Django 5.2 on 2025-08-24 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_selfiewithtree'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selfiewithtree',
            name='is_verified',
        ),
        migrations.AddField(
            model_name='selfiewithtree',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='selfiewithtree',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='selfiewithtree',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tree_selfie', to=settings.AUTH_USER_MODEL),
        ),
    ]
